### ISSUE TITLE
Enrich profile based on ip

### ISSUE THREAD

**Issue by damienbrz** [damienbrz/enrichment#3]
### Service used:
http://dev.maxmind.com/geoip/geoip2/web-services/

Calling `Enrichment::Ip.insights("0.0.0.0")` should return an object with the following properties:

- [x] country
- [x] country_code
- [x] region
- [x] city
- [x] postcode
- [x] longitude
- [x] latitude
- [x] continent
- [x] time_zone

### Todo:
- [x] Update Readme
- [x] Install geoip2 gem
- [x] Setup configure block for maxmind
- [X] Specs around maxmind API
